export interface CommandDetail {
  trigger: string;
  name: string;
  agent: string;
  phase: string;
  purpose: string;
  whenToUse: string;
  example: string;
  output: string;
}

export const COMMAND_DETAILS: Record<string, CommandDetail> = {
  BP: {
    trigger: "BP",
    name: "Brainstorm Project",
    agent: "Mary (Business Analyst)",
    phase: "Analysis",
    purpose: "An interactive brainstorming session to help you explore a new product or feature idea from multiple angles — customer problems, use cases, differentiators, and risks.",
    whenToUse: "Run this first when you have a rough idea but haven't structured it yet. It's also useful when you're stuck and need to pressure-test assumptions.",
    example: "You type BP and Mary asks questions like: \"Who are the primary users?\", \"What pain does this solve that competitors don't?\", \"What's the simplest version that would still be valuable?\" After a few rounds, you'll have a clear picture of the problem space.",
    output: "A conversational exploration that sharpens your thinking. No document is produced automatically — use CB afterwards to capture the result.",
  },
  MR: {
    trigger: "MR",
    name: "Market Research",
    agent: "Mary (Business Analyst)",
    phase: "Analysis",
    purpose: "Analyzes the competitive landscape, market size, trends, and key players relevant to your product idea.",
    whenToUse: "Use after BP when you need to validate that there's an opportunity, or when you need talking points for a stakeholder pitch.",
    example: "For a Java dependency scanner aimed at banks, MR surfaces: commercial tools (Snyk, Mend), why banks avoid them (data leaving the firewall), regulatory drivers (Log4Shell, DORA), and the internal-tool dynamic that makes this space attractive.",
    output: "A structured market summary covering competitors, differentiators, regulatory context, and market timing.",
  },
  DR: {
    trigger: "DR",
    name: "Domain Research",
    agent: "Mary (Business Analyst)",
    phase: "Analysis",
    purpose: "Deep-dives into the business domain — regulations, terminology, workflows, and constraints that shape the solution.",
    whenToUse: "Use when you're building for a regulated or specialized industry (banking, healthcare, legal) and need to ground the product in real domain constraints.",
    example: "For a bank-internal tool, DR covers: SOX controls on production code, SSO/LDAP expectations, change-management workflows, and the split between AppSec, Dev, and Compliance roles.",
    output: "A domain brief that informs PRD decisions downstream.",
  },
  TR: {
    trigger: "TR",
    name: "Technical Research",
    agent: "Mary (Business Analyst)",
    phase: "Analysis",
    purpose: "Investigates the technical landscape — frameworks, libraries, APIs, and integration patterns relevant to the build.",
    whenToUse: "Use before architecture work when you're unsure what stack or third-party services to use, or when evaluating build-vs-buy.",
    example: "For an AI-powered dev tool, TR compares Anthropic Claude vs OpenAI for code-aware tasks, looks at SonarQube vs custom AST parsing, and summarizes the cost/latency trade-offs.",
    output: "A technical options brief with recommendations.",
  },
  CB: {
    trigger: "CB",
    name: "Create Brief",
    agent: "Mary (Business Analyst)",
    phase: "Analysis",
    purpose: "Produces a structured Product Brief document that captures the problem, target users, value proposition, and constraints.",
    whenToUse: "Run this at the end of the Analysis phase to lock in what you learned. The Brief is input for the PRD.",
    example: "After BP and MR on a bank tool, CB produces a Brief with sections like Problem Statement, Target Personas (Developer, Director, AppSec), Success Metrics, and Out of Scope.",
    output: "A saved Brief document in the Documents panel.",
  },
  CP: {
    trigger: "CP",
    name: "Create PRD",
    agent: "John (Product Manager)",
    phase: "Planning",
    purpose: "Guided interview that produces a full Product Requirements Document with features, user stories, acceptance criteria, and non-functional requirements.",
    whenToUse: "Run after the Brief is ready. The PRD is the central document every other phase refers to.",
    example: "John asks about must-have features, nice-to-haves, user journeys, and edge cases. You confirm or correct, and he assembles a PRD covering feature list, user flows, NFRs (performance, security, accessibility), and open questions.",
    output: "A saved PRD document.",
  },
  VP: {
    trigger: "VP",
    name: "Validate PRD",
    agent: "John (Product Manager)",
    phase: "Planning",
    purpose: "Reviews the PRD for gaps, ambiguities, and missing acceptance criteria. Flags features without clear success metrics.",
    whenToUse: "Run immediately after CP and before CA. Catching issues now prevents rework in architecture and stories.",
    example: "VP might flag: \"Feature X has no error-path AC\", \"NFR for latency is missing\", \"User role Y is referenced but not defined.\"",
    output: "A validation report with specific issues to resolve, plus an updated PRD once you accept the changes.",
  },
  EP: {
    trigger: "EP",
    name: "Edit PRD",
    agent: "John (Product Manager)",
    phase: "Planning",
    purpose: "Targeted edits to the PRD — add a feature, change a requirement, or rework a section.",
    whenToUse: "Any time requirements change after the initial PRD is written.",
    example: "\"EP: add a feature for PDF export of scan results, targeting Compliance users.\" John updates the relevant sections and regenerates the document.",
    output: "Updated PRD document.",
  },
  CU: {
    trigger: "CU",
    name: "Create UX Design",
    agent: "Sally (UX Designer)",
    phase: "Planning",
    purpose: "Produces a UX document with screen flows, key views, states (loading/error/empty), and interaction patterns.",
    whenToUse: "Run after the PRD. The UX doc feeds into architecture (what screens/APIs are needed) and stories.",
    example: "For a dev tool, Sally drafts screens for: repo list, scan progress, fix review with diff viewer, and PR submission. Each screen notes empty/error states and keyboard shortcuts.",
    output: "A saved UX Design document.",
  },
  CA: {
    trigger: "CA",
    name: "Create Architecture",
    agent: "Winston (Lead Architect)",
    phase: "Solutioning",
    purpose: "Defines the technical architecture: components, data model, integrations, deployment model, and key trade-offs.",
    whenToUse: "Run after the PRD and UX are stable. Architecture should reflect real requirements, not guesses.",
    example: "Winston produces: system diagram, tech stack (Spring Boot + React + Postgres), data model (users, scans, findings), integration points (SonarQube, Bedrock), and security model (JWT, per-tenant schemas).",
    output: "A saved Architecture document.",
  },
  CE: {
    trigger: "CE",
    name: "Create Epics & Stories",
    agent: "John (Product Manager)",
    phase: "Solutioning",
    purpose: "Breaks the PRD, UX, and Architecture into epics and stories with acceptance criteria, priorities, and story point estimates — in a format the Board can import.",
    whenToUse: "Run once CA is complete. This is the bridge from docs to the Board.",
    example: "Produces epics like \"E1 — Authentication & Access\" with stories like \"Story E1.1: SSO login via LDAP\" including description, acceptance criteria (Given/When/Then), priority, and points.",
    output: "A saved Epics & Stories document. Click Import from Documents on the Board to load them.",
  },
  IR: {
    trigger: "IR",
    name: "Implementation Readiness Check",
    agent: "Winston (Lead Architect)",
    phase: "Solutioning",
    purpose: "Verifies the PRD, UX, and Architecture are aligned and complete enough to start building. Surfaces contradictions and gaps.",
    whenToUse: "Run after CE and before sprint planning. It's a final gate before implementation.",
    example: "IR might report: \"PRD says offline mode; Architecture assumes always-online — resolve\"; \"UX shows multi-select but no API supports it.\"",
    output: "A readiness report with a go/no-go recommendation.",
  },
  FD: {
    trigger: "FD",
    name: "Find Dependencies",
    agent: "Fred (Sprint Planner)",
    phase: "Refinement",
    purpose: "Analyzes all stories and maps dependencies — which stories block or enable others. Results are saved as links on the stories themselves.",
    whenToUse: "Run after importing stories to the Board, before sprint planning.",
    example: "Fred might find: \"Story E4.2 (scan engine) depends on E1.1 (auth) and E3.1 (repo connect)\" and links them so you can't plan E4.2 into a sprint before its blockers.",
    output: "Dependency links between stories, visible on each story card.",
  },
  IN: {
    trigger: "IN",
    name: "INVEST Review",
    agent: "Allie (Story Coach)",
    phase: "Refinement",
    purpose: "Scores each story against the INVEST framework — Independent, Negotiable, Valuable, Estimable, Small, Testable — and suggests rewrites for weak stories.",
    whenToUse: "Run after FD, before sprint planning. Catches ambiguous, too-large, or untestable stories.",
    example: "For a story like \"Improve performance\", Allie flags it as not Valuable (vague) and not Testable (no metric), and suggests: \"Reduce scan latency for repos under 1k files from 30s to 5s at p95.\"",
    output: "INVEST scores and rewrite suggestions on each story.",
  },
  SP: {
    trigger: "SP",
    name: "Sprint Planning",
    agent: "Fred (Sprint Planner)",
    phase: "Refinement",
    purpose: "Proposes balanced sprints from the backlog, respecting dependencies, priority, and team capacity.",
    whenToUse: "After FD and IN. Fred can plan one sprint or a multi-sprint roadmap.",
    example: "Given 80 points of capacity over 2 sprints, Fred proposes Sprint 1 (foundation epics) and Sprint 2 (features that depend on them), with rationale for each choice.",
    output: "A sprint plan that you can accept and apply to the Board.",
  },
  CS: {
    trigger: "CS",
    name: "Context Story",
    agent: "Bob (Scrum Master)",
    phase: "Implementation",
    purpose: "Prepares a single story with full implementation context — relevant PRD sections, architecture notes, and code pointers — so a developer can start immediately.",
    whenToUse: "Before a developer picks up a story, especially for new team members.",
    example: "For \"Story E4.2: Scan worker\", CS produces a brief that pulls in the relevant architecture sections (async thread pool config), the data model (scan_jobs table), and acceptance criteria all in one place.",
    output: "A context-rich implementation brief attached to the story.",
  },
  DS: {
    trigger: "DS",
    name: "Dev Story",
    agent: "DevAI (Developer)",
    phase: "Implementation",
    purpose: "Writes test cases and a code outline for a specific story — methods, classes, signatures, and test scaffolding.",
    whenToUse: "Once a story has implementation context (CS), run DS to get a starting point for the code.",
    example: "For a Spring service, DS produces: the service class signature, repository interfaces, test fixtures, and JUnit test skeletons covering the acceptance criteria.",
    output: "A code outline and test plan — not runnable code, but a strong scaffold.",
  },
  CR: {
    trigger: "CR",
    name: "Code Review",
    agent: "Quinn (QA Engineer)",
    phase: "Implementation",
    purpose: "Reviews a diff or a code snippet against the story's acceptance criteria, plus general code quality, security, and style.",
    whenToUse: "Before merging a PR, or as a self-check before opening one.",
    example: "Paste a diff with CR and Quinn returns: \"AC 1 and 2 are covered; AC 3 (error path) has no test; potential SQL injection at line X; naming suggestion at Y.\"",
    output: "A review with severity-labeled findings.",
  },
  QA: {
    trigger: "QA",
    name: "QA Automate",
    agent: "Quinn (QA Engineer)",
    phase: "Implementation",
    purpose: "Generates automated test cases (unit, integration, or E2E) for a story's acceptance criteria.",
    whenToUse: "After DS and CR, when you need to lock in behavior with tests.",
    example: "For a login story, QA produces unit tests for the auth service, integration tests for the /login endpoint, and a Playwright E2E for the happy path.",
    output: "Test code you can drop into your repo.",
  },
  CC: {
    trigger: "CC",
    name: "Course Correction",
    agent: "Bob (Scrum Master)",
    phase: "Implementation",
    purpose: "Mid-sprint replan — recover from blockers, scope changes, or missed estimates without derailing the sprint.",
    whenToUse: "When a sprint is clearly off-track and you need to rebalance.",
    example: "\"Story X is blocked on a third-party delay. Pull it out, bring in Story Y from the next sprint, and note the impact.\" Bob produces the revised plan and comms draft.",
    output: "A revised sprint plan and stakeholder note.",
  },
  ER: {
    trigger: "ER",
    name: "Epic Retrospective",
    agent: "Bob (Scrum Master)",
    phase: "Implementation",
    purpose: "Retrospective on a completed epic — what went well, what to improve, and what to carry forward.",
    whenToUse: "Right after an epic's final story ships.",
    example: "ER surfaces patterns like \"Estimation was off by 40% on stories that crossed frontend/backend\" and proposes a concrete action: \"Split cross-stack stories into two.\"",
    output: "A retrospective document with actions.",
  },
};
